govno
BPL-Company/admin-bot pull request #5
Opened 2020-10-03 17:14 UTC by Vezono

2020-10-03 17:38 UTC, p0lunin requested changes

2020-10-03 17:38 UTC, p0lunin commented on handlers/antispam.py
> +            user = users_repo.create_user(tg_user.id, 'user')
You can use `user_service.create_user_if_need()` (https://github.com/BPL-Company/admin-bot/blob/master/services/users.py#L152)

2020-10-03 17:38 UTC, p0lunin commented on services/greeter.py
> +greeter = Greeter()
Services must be created in [startup.py](https://github.com/BPL-Company/admin-bot/blob/master/startup.py)

2020-10-03 17:38 UTC, p0lunin commented on services/greeter.py
> +    def form_session(self) -> World:
I think `create` will be better than `form`

2020-10-03 17:38 UTC, p0lunin commented on services/greeter.py
> +        self.greeted_users = set()
Why we need an set with users if we now have them in greet_sessions?

2020-10-04 08:34 UTC, Vezono commented on services/greeter.py
> +        self.greeted_users = set()
так надо

2020-10-04 13:36 UTC, Vezono commented on services/greeter.py
> +        self.greeted_users = set()
ДА ТАК НАДО НАДО

2020-10-04 13:36 UTC, Vezono commented on services/greeter.py
> +        self.greeted_users = set()
То сессии а это айдишники

2020-10-04 13:38 UTC, Vezono commented on services/greeter.py
> +        self.greeted_users = set()
Мне похуй либо принимай либо саси

2020-10-04 13:38 UTC, Vezono commented on services/greeter.py
> +        self.greeted_users = set()
Вот такой бпльный энтерпррпрайз

2020-10-04 13:43 UTC, merged

2020-10-04 14:00 UTC, Vezono commented
УРА МЕРЖЕД